#!/sbin/busybox sh

# $1 - "input_boost_freq_01"
# $2 - value=
# Created By Alucard24

if [ "a$2" != "a" ]; then
	input_boost_freq_01=$2;

	echo "0:$input_boost_freq_01" > /sys/module/alu_t_boost/parameters/input_boost_freq;
fi;

echo ${input_boost_freq_01};
