#!/sbin/busybox sh

# $1 - "scaling_governor_cpu01"
# $2 - value=
# Created By Dorimanx

# get values from profile
PROFILE=$(cat /data/.alucard/.active.profile);
. /data/.alucard/"$PROFILE".profile;

if [ "a$2" != "a" ]; then
	scaling_governor_cpu01=$2;

	# Force unmask hotplugged cpus
	echo 1 > /sys/module/msm_thermal/core_control/force_unmask;
	# disable thermal bcl hotplug to switch governor;
	echo 0 > /sys/module/msm_thermal/core_control/enabled;
	echo -n disable > /sys/devices/soc/soc:qcom,bcl/mode;
	bcl_hotplug_mask=`cat /sys/devices/soc/soc:qcom,bcl/hotplug_mask`;
	echo 0 > /sys/devices/soc/soc:qcom,bcl/hotplug_mask;
	bcl_soc_hotplug_mask=`cat /sys/devices/soc/soc:qcom,bcl/hotplug_soc_mask`;
	echo 0 > /sys/devices/soc/soc:qcom,bcl/hotplug_soc_mask;
	echo -n enable > /sys/devices/soc/soc:qcom,bcl/mode;

	echo "$scaling_governor_cpu01" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;

	# re-enable thermal and BCL hotplug;
	echo 1 > /sys/module/msm_thermal/core_control/enabled;
	echo -n disable > /sys/devices/soc/soc:qcom,bcl/mode;
	echo "$bcl_hotplug_mask" > /sys/devices/soc/soc:qcom,bcl/hotplug_mask;
	echo "$bcl_soc_hotplug_mask" > /sys/devices/soc/soc:qcom,bcl/hotplug_soc_mask;
	echo -n enable > /sys/devices/soc/soc:qcom,bcl/mode;
	# recover offlined_mask in thermal.
	echo 0 > /sys/module/msm_thermal/core_control/force_unmask;
fi;

echo ${scaling_governor_cpu01};
