#!/sbin/busybox sh

(
	/sbin/ext/cortexbrain-tune.sh apply_cpu_load update > /dev/null;

	SYSTEM_GOVERNOR_01=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor);
	SYSTEM_GOVERNOR_23=$(cat /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor);

	rm /data/.alucard/cpu_load_status;
	cd /sys/devices/system/cpu/cpu0/cpufreq/$SYSTEM_GOVERNOR_01/;
	echo "Tuning applied to '$SYSTEM_GOVERNOR_01' core!" >> /data/.alucard/cpu_load_status;
	grep "." * >> /data/.alucard/cpu_load_status;
	cd /sys/devices/system/cpu/cpu2/cpufreq/$SYSTEM_GOVERNOR_23/;
	echo "Tuning applied to '$SYSTEM_GOVERNOR_23' core!" >> /data/.alucard/cpu_load_status;
	grep "." * >> /data/.alucard/cpu_load_status;
	cd /;
)&
sleep 2;
CPU_LOAD_LOG=`cat /data/.alucard/cpu_load_status`;
echo $CPU_LOAD_LOG;
