#!/sbin/busybox sh

(
	/sbin/ext/cortexbrain-tune.sh apply_sched update > /dev/null;

	rm /data/.alucard/sched_status;
	cd /proc/sys/kernel/;
	echo "Tuning applied to sched!" >> /data/.alucard/sched_status;
	grep "." * >> /data/.alucard/sched_status;
	cd /;
)&
sleep 2;
SCHED_LOG=`cat /data/.alucard/sched_status`;
echo $SCHED_LOG;
